#!/usr/bin/env bash

interface=$1
action=$2

if [ "$interface" = "eth0" -a "$action" = "up" ]
then
    metadata_host_name=$(/usr/local/bin/oc-metadata --cached HOSTNAME)
    if [ "x$metadata_host_name" != "x" ]
    then
	echo $metadata_host_name > /etc/hostname
	sed "/^127.0.1.1[ \t].*$/ s/.*$/127.0.1.1\t$metadata_host_name/" -i /etc/hosts
	sed "/^127.0.0.1[ \t]localhost/ s/localhost.*$/localhost $metadata_host_name/" -i /etc/hosts
	hostnamectl set-hostname $metadata_host_name
    fi
fi
